// <auto-generated />
using AspSite.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AspSite.Api.Data.Migrations
{
    [DbContext(typeof(toDoContext))]
    [Migration("20250831202708_seedUrgency")]
    partial class seedUrgency
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("AspSite.Api.Entities.Urgency", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("descr")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("level")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("Urgencies");

                    b.HasData(
                        new
                        {
                            id = 1,
                            descr = "Lowest",
                            level = 1
                        },
                        new
                        {
                            id = 2,
                            descr = "Low",
                            level = 2
                        },
                        new
                        {
                            id = 3,
                            descr = "Medium",
                            level = 3
                        },
                        new
                        {
                            id = 4,
                            descr = "High",
                            level = 4
                        },
                        new
                        {
                            id = 5,
                            descr = "Highest",
                            level = 5
                        });
                });

            modelBuilder.Entity("AspSite.Api.Entities.toDo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("isDone")
                        .HasColumnType("INTEGER");

                    b.Property<string>("task")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("urgencyId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("urgencyId");

                    b.ToTable("toDos");
                });

            modelBuilder.Entity("AspSite.Api.Entities.toDo", b =>
                {
                    b.HasOne("AspSite.Api.Entities.Urgency", "Urgency")
                        .WithMany()
                        .HasForeignKey("urgencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Urgency");
                });
#pragma warning restore 612, 618
        }
    }
}
