// <auto-generated />
using AspSite.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AspSite.Api.Data.Migrations
{
    [DbContext(typeof(toDoContext))]
    [Migration("20250831202127_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("AspSite.Api.Entities.Urgency", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descr")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("level")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("Urgencies");
                });

            modelBuilder.Entity("AspSite.Api.Entities.toDo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("isDone")
                        .HasColumnType("INTEGER");

                    b.Property<string>("task")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("urgencyId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("urgencyId");

                    b.ToTable("toDos");
                });

            modelBuilder.Entity("AspSite.Api.Entities.toDo", b =>
                {
                    b.HasOne("AspSite.Api.Entities.Urgency", "Urgency")
                        .WithMany()
                        .HasForeignKey("urgencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Urgency");
                });
#pragma warning restore 612, 618
        }
    }
}
